// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
   numberOfOrders:          number;
   paidOrders:              number;
   notPaidOrders:           number;
   numbersOfClients:        number;
   numberOfProducts:        number;
   productsWithNoInventory: number;
   lowInventory:            number;
}
